#!/usr/bin/env python3
"""Generate one email signature per attorney, from the site's own team data.

    python3 src/signature/make_signatures.py

Writes src/signature/signature-<slug>.html. Names, roles, emails and phone
numbers come from site_content.TEAM, so the signatures cannot drift from the
website; change a number there and regenerate.

Badges: the Chambers and Lawyer of the Year artwork name Sean personally, so
they appear only in his signature. Everyone else carries the firm-level Best
Law Firms badge and the Spotlight Firm line. Putting a colleague's personal
award in someone else's signature would misattribute it.
"""
import os, sys, html as _html
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
from site_content import TEAM, FIRM

OUT = HERE
BASE = FIRM["domain"] + "/assets/img"
esc = lambda s: _html.escape(s, quote=True)

PERSONAL_BADGES = [
    ("badge-chambers-2026.png", "Chambers USA Top Ranked 2026", 100, 84),
    ("badge-best-lawyers-loty-2026.png", "Best Lawyers Lawyer of the Year 2026", 75, 84),
]
FIRM_BADGES = [("badge-best-law-firms-2026.png", "Best Law Firms 2026", 72, 84)]

def phone_lines(t):
    """site_content stores phones as '513.694.7501 (d) · 513.235.3470 (c)'."""
    label = {"d": "direct", "c": "cell", "o": "office"}
    out = []
    for part in t["phones"].split("·"):
        part = part.strip()
        num, _, tag = part.partition(" ")
        out.append((num, label.get(tag.strip("()"), "")))
    if not any(n == FIRM["phone"] for n, _ in out):
        out.append((FIRM["phone"], "office"))
    order = {"direct": 0, "cell": 1, "office": 2}
    return sorted(out, key=lambda p: order.get(p[1], 3))

def badge_row(badges):
    cells = ""
    for i, (img, alt, w, h) in enumerate(badges):
        pad = "0 16px 0 0" if i < len(badges) - 1 else "0"
        cells += (f'\n          <td style="padding:{pad}" valign="bottom">'
                  f'<img src="{BASE}/{img}" alt="{esc(alt)}" width="{w}" height="{h}" '
                  f'style="display:block;border:0"></td>')
    return cells

def signature(t):
    attorney = "non-attorney" not in t["role"]
    name = f'{esc(t["name"])}, <span style="font-size:15px">Esq.</span>' if attorney else esc(t["name"])
    # the site's role can carry a qualifier ("Managing Member / Founder"); a
    # signature uses the title itself, which is what Sean's own signature showed
    role = t["role"].replace(" (non-attorney)", "").split(" / ")[0]
    badges = (PERSONAL_BADGES + FIRM_BADGES) if t["slug"] == "sean-suder" else FIRM_BADGES
    phones = "\n      &nbsp;<span style=\"color:#c9ccd1\">|</span>&nbsp;\n".join(
        f'      <a href="tel:+1{num.replace(".", "")}" style="color:#1d2229;text-decoration:none">{num}</a> {lab}'.lstrip()
        for num, lab in phone_lines(t))
    return f'''<!-- Suder, LLC email signature — {esc(t["name"])}
     Generated by src/signature/make_signatures.py — edit that, not this file.
     Table layout and inline styles only: Outlook, Gmail and Apple Mail all strip
     <style> blocks, classes and flex/grid. Images are absolute URLs so they resolve
     in the recipient's client. Regenerate the tagline GIF with make_gif.py. -->
<table cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;width:600px;max-width:600px;font-family:Arial,Helvetica,sans-serif;color:#1d2229">
  <tr>
    <td style="padding:0 0 10px">
      <img src="{BASE}/logo-dark.png" alt="Suder, LLC" width="176" height="48" style="display:block;border:0;outline:none;text-decoration:none">
    </td>
  </tr>
  <tr>
    <td style="padding:0 0 14px">
      <img src="{BASE}/signature-tagline-reel.gif" alt="Counsel for the Built Environment." width="381" height="41" style="display:block;border:0;outline:none;text-decoration:none">
    </td>
  </tr>
  <tr><td style="padding:0 0 14px"><table cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;width:100%"><tr><td style="height:2px;line-height:2px;font-size:0;background:#b9924a">&nbsp;</td></tr></table></td></tr>
  <tr>
    <td style="padding:0 0 4px;font-family:Georgia,'Times New Roman',serif;font-size:19px;line-height:1.25;color:#15243b">
      {name}
    </td>
  </tr>
  <tr>
    <td style="padding:0 0 10px;font-size:12px;line-height:1.5;letter-spacing:.09em;text-transform:uppercase;color:#6b7280">
      {esc(role)}
    </td>
  </tr>
  <tr>
    <td style="padding:0 0 14px;font-size:13px;line-height:1.7;color:#1d2229">
{phones}<br>
      <a href="mailto:{t["email"]}" style="color:#b9924a;text-decoration:none">{esc(t["email"])}</a>
      &nbsp;<span style="color:#c9ccd1">|</span>&nbsp;
      <a href="{FIRM["domain"]}" style="color:#b9924a;text-decoration:none">www.ssuder.com</a><br>
      <span style="color:#6b7280">1502 Vine Street, 4th Floor, Cincinnati, Ohio 45202</span>
    </td>
  </tr>
  <tr>
    <td style="padding:0 0 10px">
      <table cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse">
        <tr>{badge_row(badges)}
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td style="padding:0 0 14px;font-family:Georgia,'Times New Roman',serif;font-style:italic;font-size:13px;line-height:1.5;color:#15243b">
      Chambers USA Spotlight Firm, Real Estate &mdash; Cincinnati 2025 &amp; 2026
    </td>
  </tr>
  <tr><td style="padding:0 0 10px"><table cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;width:100%"><tr><td style="height:1px;line-height:1px;font-size:0;background:#dcdfe3">&nbsp;</td></tr></table></td></tr>
  <tr>
    <td style="font-size:10.5px;line-height:1.55;color:#6b7280">
      <strong style="color:#4b5159">Notice to non-clients:</strong> Please do not send Suder, LLC any information you wish to keep confidential. Our law firm does not represent you as a client until you have completed our formal intake process. If you are not the intended recipient of this email, please delete it immediately.
      <br><br>
      <strong style="color:#4b5159">Notice to current clients:</strong> This email may contain confidential and legally privileged information for your viewing only. If you provide this email or its contents to any third party, including artificial intelligence (AI), a court may conclude that you have waived any claim to confidentiality or privilege.
    </td>
  </tr>
</table>
'''

if __name__ == "__main__":
    for t in TEAM:
        if "non-attorney" in t["role"]:
            print(f'skipped {t["name"]} — listed as a non-attorney, and on a thezoneco.com address')
            continue
        p = OUT / f'signature-{t["slug"]}.html'
        p.write_text(signature(t), encoding="utf-8")
        badges = 3 if t["slug"] == "sean-suder" else 1
        print(f'{p.name:34} {t["name"]:18} {badges} badge(s)')
